# Generated by Django 6.0.2 on 2026-03-02 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_categories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
    ]
